// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/hieronimusbudi/simple-go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// IGathering is an autogenerated mock type for the IGathering type
type IGathering struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, gathering
func (_m *IGathering) Create(ctx context.Context, gathering domain.Gathering) (int64, error) {
	ret := _m.Called(ctx, gathering)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Gathering) (int64, error)); ok {
		return rf(ctx, gathering)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Gathering) int64); ok {
		r0 = rf(ctx, gathering)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Gathering) error); ok {
		r1 = rf(ctx, gathering)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, args
func (_m *IGathering) Delete(ctx context.Context, args domain.GatheringArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GatheringArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, args
func (_m *IGathering) Get(ctx context.Context, args domain.GatheringArgs) ([]domain.Gathering, error) {
	ret := _m.Called(ctx, args)

	var r0 []domain.Gathering
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.GatheringArgs) ([]domain.Gathering, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.GatheringArgs) []domain.Gathering); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Gathering)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.GatheringArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, gathering
func (_m *IGathering) Update(ctx context.Context, gathering domain.Gathering) error {
	ret := _m.Called(ctx, gathering)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Gathering) error); ok {
		r0 = rf(ctx, gathering)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIGathering creates a new instance of IGathering. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGathering(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGathering {
	mock := &IGathering{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
