// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/hieronimusbudi/simple-go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// IInvitation is an autogenerated mock type for the IInvitation type
type IInvitation struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, invitation
func (_m *IInvitation) Create(ctx context.Context, invitation domain.Invitation) (int64, error) {
	ret := _m.Called(ctx, invitation)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) (int64, error)); ok {
		return rf(ctx, invitation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) int64); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Invitation) error); ok {
		r1 = rf(ctx, invitation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, args
func (_m *IInvitation) Get(ctx context.Context, args domain.InvitationArgs) ([]domain.Invitation, error) {
	ret := _m.Called(ctx, args)

	var r0 []domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) ([]domain.Invitation, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) []domain.Invitation); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InvitationArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, args
func (_m *IInvitation) UpdateStatus(ctx context.Context, args domain.InvitationArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIInvitation creates a new instance of IInvitation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInvitation(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInvitation {
	mock := &IInvitation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
