// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/hieronimusbudi/simple-go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// IInvitationUsecase is an autogenerated mock type for the IInvitationUsecase type
type IInvitationUsecase struct {
	mock.Mock
}

// Accept provides a mock function with given fields: ctx, args
func (_m *IInvitationUsecase) Accept(ctx context.Context, args domain.InvitationArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cancel provides a mock function with given fields: ctx, args
func (_m *IInvitationUsecase) Cancel(ctx context.Context, args domain.InvitationArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, invitation
func (_m *IInvitationUsecase) Create(ctx context.Context, invitation domain.Invitation) (domain.Invitation, error) {
	ret := _m.Called(ctx, invitation)

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) (domain.Invitation, error)); ok {
		return rf(ctx, invitation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Invitation) domain.Invitation); ok {
		r0 = rf(ctx, invitation)
	} else {
		r0 = ret.Get(0).(domain.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Invitation) error); ok {
		r1 = rf(ctx, invitation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, args
func (_m *IInvitationUsecase) Get(ctx context.Context, args domain.InvitationArgs) ([]domain.Invitation, error) {
	ret := _m.Called(ctx, args)

	var r0 []domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) ([]domain.Invitation, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) []domain.Invitation); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.InvitationArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *IInvitationUsecase) GetByID(ctx context.Context, id int64) (domain.Invitation, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Invitation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (domain.Invitation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Invitation); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Invitation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reject provides a mock function with given fields: ctx, args
func (_m *IInvitationUsecase) Reject(ctx context.Context, args domain.InvitationArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.InvitationArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIInvitationUsecase creates a new instance of IInvitationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIInvitationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *IInvitationUsecase {
	mock := &IInvitationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
