// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/hieronimusbudi/simple-go-api/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// IMember is an autogenerated mock type for the IMember type
type IMember struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, member
func (_m *IMember) Create(ctx context.Context, member domain.Member) (int64, error) {
	ret := _m.Called(ctx, member)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Member) (int64, error)); ok {
		return rf(ctx, member)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Member) int64); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Member) error); ok {
		r1 = rf(ctx, member)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, args
func (_m *IMember) Delete(ctx context.Context, args domain.MemberArgs) error {
	ret := _m.Called(ctx, args)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MemberArgs) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, args
func (_m *IMember) Get(ctx context.Context, args domain.MemberArgs) ([]domain.Member, error) {
	ret := _m.Called(ctx, args)

	var r0 []domain.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.MemberArgs) ([]domain.Member, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.MemberArgs) []domain.Member); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.MemberArgs) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, member
func (_m *IMember) Update(ctx context.Context, member domain.Member) error {
	ret := _m.Called(ctx, member)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Member) error); ok {
		r0 = rf(ctx, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMember creates a new instance of IMember. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMember(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMember {
	mock := &IMember{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
